name: ai-review-bot
description: Composite Action – GPT-4 code review

inputs:
  openai_api_key:
    required: true
    description: OpenAI API Key

runs:
  using: composite
  steps:
    # Ambiente Python
    - uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: pip

    # Instalar deps do bot
    - run: pip install -r "${{ github.action_path }}/requirements.txt"
      shell: bash

    # Rodar orquestrador
    - env:
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        GITHUB_BASE_SHA: ${{ github.event.pull_request.base.sha }}
        GITHUB_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      run: python "${{ github.action_path }}/scripts/ai_orchestrator.py" --mode diff > review.md
      shell: bash

    # Comentário sticky
    - uses: marocchino/sticky-pull-request-comment@v2
      with:
        GITHUB_TOKEN: ${{ github.token }}
        path: review.md
