name: AI Review

# ➜ 2 gatilhos: PR normal + comentário "/ai-review"
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write

jobs:
  call-review:
    # Só roda se for (a) evento de PR  OU
    # (b) comentário "/ai-review" dentro de uma PR
    if: |
      github.event_name == 'pull_request' ||
      (
        github.event_name == 'issue_comment' &&
        github.event.comment.body == '/ai-review' &&
        github.event.issue.pull_request
      )

    uses: ./.github/workflows/callable.yml
    secrets:
      openai_api_key: ${{ secrets.OPENAI_API_KEY }}
