name: AI Review

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write      # <- REQUIRED for commenting

jobs:
  ai-review:
    if: |
      github.event_name == 'pull_request_target' ||
      (
        github.event_name == 'issue_comment' &&
        contains(github.event.comment.body, '/ai-review') &&
        github.event.issue.pull_request
      )
    uses: synapscale/ai-review-bot/.github/workflows/callable.yml@v2.2
    with:
      openai_api_key: ${{ secrets.OPENAI_API_KEY }}
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # garante GITHUB_TOKEN no filho
    # checkout já acontece dentro do callable.yml;
    # nele deve constar:
    # - uses: actions/checkout@v4
    #   with:
    #     repository: ${{ github.event.pull_request.head.repo.full_name }}
    #     ref:        ${{ github.event.pull_request.head.ref }}
    #     fetch-depth: 0