name: AI Review (Reusable)

on:
  workflow_call:
    secrets:
      openai_api_key:
        required: true

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      # ①  Código da PR — branch do autor (seguro p/ forks)
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref:        ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      # ②  Código do bot em subpasta
      - name: Checkout AI Review Bot
        uses: actions/checkout@v4
        with:
          repository: synapscale/ai-review-automation   # <— este repo
          ref:        main                              # ou v2.1 quando taggear
          path:       ai-review-bot

      # ③  Ambiente Python + cache
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      # ④  Dependências do bot
      - run: pip install -r ai-review-bot/requirements.txt

      # ⑤  Executar orquestrador
      - name: Run AI Orchestrator
        env:
          OPENAI_API_KEY: ${{ secrets.openai_api_key }}
          GITHUB_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: python ai-review-bot/scripts/ai_orchestrator.py --mode diff > review.md

      # ⑥  Comentar / atualizar relatório sticky
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ github.token }}
          path: review.md
